logger:
  level: info

db:
  dsn: "postgres://calendar:calendar@localhost:5432/calendar?sslmode=disable"

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  queue_name: "notifications"

scheduler:
  interval: 1m  # интервал сканирования (1 минута)

